[project]
name = "myliquidenginepackage"
version = "0.1.0"

requires-python = ">=3.9"

license = {file = "LICENSE.txt"}

dependencies = [
    "Cython",
    "nanopyx"
]


[build-system]
requires = ["setuptools>=43.0.0", "wheel", "cython", "build"]
build-backend = "setuptools.build_meta"